# get transcript/subtitles/captions using youtube_transcript_api
from youtube_transcript_api import YouTubeTranscriptApi

# get_transcript(video_id) function
video_id = "4VNz4lOglj8"
YouTubeTranscriptApi.get_transcript(video_id)

# retrieve the available transcripts
transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)

# iterate over all available transcripts
for transcript in transcript_list:
    # the Transcript object provides metadata properties
    print(
        transcript.video_id,
        transcript.language,
        transcript.language_code,
        # whether it has been manually created or generated by YouTube
        transcript.is_generated,
        # whether this transcript can be translated or not
        transcript.is_translatable,
        # a list of languages the transcript can be translated to
        transcript.translation_languages,
    )
    # fetch the actual transcript data
    print(transcript.fetch())

    # translating the transcript will return another transcript object
    print(transcript.translate('zh-Hans').fetch())
